export default {
    LOAD_APPLICATION_DOMAIN: 'LOAD_APPLICATION_DOMAIN',
    LOAD_APPLICATION_DOMAIN_SUCCESS: 'LOAD_APPLICATION_DOMAIN_SUCCESS',
    LOAD_APPLICATION_DOMAIN_FAILED: 'LOAD_APPLICATION_DOMAIN_FAILED'
};