export default {
    LOAD_ENTITY: 'LOAD_ENTITY',
    LOAD_ENTITY_SUCCESS: 'LOAD_ENTITY_SUCCESS',
    LOAD_ENTITY_FAIL: 'LOAD_ENTITY_FAIL',
    SAVE_ENTITY: 'SAVE_ENTITY',
    SAVE_ENTITY_SUCCESS: 'SAVE_ENTITY_SUCCESS',
    SAVE_ENTITY_FAIL: 'SAVE_ENTITY_FAIL'
};