export default {
    SAVE_ENTITY: 'SAVE_ENTITY',
    SAVE_ENTITY_SUCCESS: 'SAVE_ENTITY_SUCCESS',
    SAVE_ENTITY_FAILED: 'SAVE_ENTITY_FAILED',
    LOAD_ENTITY: 'LOAD_ENTITY',
    LOAD_ENTITY_SUCCESS: 'LOAD_ENTITY_SUCCESS',
    LOAD_ENTITY_FAILED: 'LOAD_ENTITY_FAILED'
};