export default { provider: 'google',
    id: '109199054588840596357',
    displayName: 'André Pena',
    name: { familyName: 'Pena', givenName: 'André' },
    emails: [ { value: 'andrerpena@gmail.com', type: 'account' } ],
    photos: [ { value: 'https://lh3.googleusercontent.com/-H2ScI8V-1xg/AAAAAAAAAAI/AAAAAAAAAH8/TrBfrK-b_7k/photo.jpg?sz=50' } ],
    gender: 'male',
    _raw: '{\n "kind": "plus#person",\n "etag": "\\"RqKWnRU4WW46-6W3rWhLR9iFZQM/0J0WDPsQugjfgxQx1uQUujv036M\\"",\n "gender": "male",\n "emails": [\n  {\n   "value": "andrerpena@gmail.com",\n   "type": "account"\n  }\n ],\n "urls": [\n  {\n   "value": "https://profiles.google.com/109199054588840596356/buzz",\n   "type": "contributor",\n   "label": "Buzz"\n  }\n ],\n "objectType": "person",\n "id": "109199054588840596356",\n "displayName": "André Pena",\n "name": {\n  "familyName": "Pena",\n  "givenName": "André"\n },\n "url": "https://plus.google.com/109199054588840596356",\n "image": {\n  "url": "https://lh3.googleusercontent.com/-H2ScI8V-1xg/AAAAAAAAAAI/AAAAAAAAAH8/TrBfrK-b_7k/photo.jpg?sz=50",\n  "isDefault": false\n },\n "isPlusUser": true,\n "language": "en",\n "circledByCount": 68,\n "verified": false\n}\n',
    _json:
    { kind: 'plus#person',
        etag: '"RqKWnRU4WW46-6W3rWhLR9iFZQM/0J0WDPsQugjfgxQx1uQUujv036M"',
        gender: 'male',
        emails: [ { value: 'andrerpena@gmail.com', type: 'account' } ],
        objectType: 'person',
        id: '109199054588840596357',
        displayName: 'André Pena',
        name: { familyName: 'Pena', givenName: 'André' },
        url: 'https://plus.google.com/109199054588840596356',
        image:
        { url: 'https://lh3.googleusercontent.com/-H2ScI8V-1xg/AAAAAAAAAAI/AAAAAAAAAH8/TrBfrK-b_7k/photo.jpg?sz=50',
            isDefault: false },
        isPlusUser: true,
        language: 'en',
        circledByCount: 68,
        verified: false } };
